### ISSUE TITLE
How to authenticate normal login

### ISSUE THREAD

**Issue by fabiantorresm** [utsavstha/adonis-websocket-client-android#1]
Hello, excuse the question, how can I secure the connection through Auth ?. For example for normal login email and password, where I place these parameters.

Thank you for your work

**Comment by utsavstha** [comment]
If you're using adonis auth; a jwt token can be sent with every request from client side and verified at server side before processing request.

**Comment by fabiantorresm** [comment]
Haber if I understood. Inside the json object ?. Where did you put username?

**Comment by utsavstha** [comment]
how are you authenticating the REST apis?

**Comment by fabiantorresm** [comment]
> ¿Cómo estás autentificando los apis REST?

Hi, i'm using Auth - jwt.
