### ISSUE TITLE
How to retrieve info from the Events?

### ISSUE THREAD

**Issue by sotoh** [utsavstha/adonis-websocket-client-android#2]
From your docs I use this:
```
socket.onEventResponse("message", new Socket.OnEventResponseListener() {
    @Override
    public void onMessage(String event, String data) {
        System.out.println(data);
    }
});
```
And in this part I can not retrieve data from the websocket, I got the message from logcat, that I received new message and I can see the data but I can not use it.

In the server I have in controller
```
'use` strict'

class GeneralController {
  constructor ({ socket, request }) {
    this.socket = socket
    this.request = request
    console.log('user joined with %s socket id', socket.id)
  }

  onMessage() {
   this.socket.broadcastToAll('message','Hello Everyone')
 }
}
````

And in socket.js
```
const Ws = use('Ws')
Ws.channel('test','GeneralController')
```

And in android:
```
protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
       Socket socket = Socket.Builder.with("ws://127.0.0.1:3333/adonis-ws").build();
       socket.connect();
}
```
Empty project with empty activity.

**Comment by utsavstha** [comment]
@sotoh hello I'm not sure what you meant by this, "received new message and I can see the data but I can not use it". Did you manage to fix this issue?

**Comment by sotoh** [comment]
In Logcat tab from Android Studio shows when new data is received but I can't access the data, I mean to save it to a var, object or array. 
So, in your repo this part is not working:
 private void output(final String txt) {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                 Toast.makeText(MainActivity.this, txt, Toast.LENGTH_SHORT).show();
                //outView.setText(outView.getText().toString() + "\n\n" + txt);
            }
        });
    }
Or perhaps am I doing something wrong?

**Comment by utsavstha** [comment]
@sotoh I just tested it again, it's working fine. Have you checked default callbacks? are those being called? Things like Socket.EVENT_OPEN.

**Comment by sotoh** [comment]
Well it was my bad. Your output function is working because it shows when is connected, now my big problem is that I cannot set/use the listener, your library only listens for onMessage event but when I want to broadcast from the server and catch the response from the server, nothing happens. 
This is my controller from the server:
` 'use strict'

class AndroidController {
  constructor ({ socket, request }) {
    this.socket = socket
    this.request = request
  }
  async onMessage(data){
    try {
      console.log(data)
      this.socket.broadcastToAll('message','Hello Everyone!')
    } catch (error) {      
    }
  }
}

module.exports = AndroidController `
The response works fine In my Angular App. Both Android and Web angular 8 are in the same socket, when I emit in both apps only in Web shows the message and android doesn't.

**Comment by sotoh** [comment]
I fixed with the following function:
```
 private void start() throws JSONException {
...
//Socket builder, connect and join functions
... 
socket.setMessageListener(new Socket.OnMessageListener() {
            @Override
            public void onMessage(String data) {
                JSONObject jsonObject = null;
                JSONObject jsonResponse = null;
                String message = "";
                try {
                   jsonObject = new JSONObject(data);
                    System.out.println(jsonObject.getInt("t"));
                    switch(jsonObject.getInt("t")){
                        case 0:break;
                        case 1:break;
                        case 2:break;
                        case 3:break;
                        case 4:break;
                        case 5:break;
                        case 6:break;
                        case 7:
                            jsonResponse = jsonObject.getJSONObject("d");
                            output(jsonResponse.getString("data"));
                            System.out.println(jsonResponse);
                            break;
                        case 8:break;
                        case 9:break;
                    }
                } catch (JSONException e) {
                    e.printStackTrace();
                }
            }
        });
  }
```
I think you missed this in your demo project, with this, now I can save the data in attributes, tags, etc.
